# Generated by Django 2.1.4 on 2019-01-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0002_auto_20190102_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
