# Generated by Django 2.1.4 on 2019-01-02 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0003_auto_20190102_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 2, 15, 26, 36, 278191)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 2, 15, 26, 36, 278162)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(blank=True, default=123),
        ),
    ]
