# Generated by Django 2.1.4 on 2019-01-02 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0004_auto_20190102_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 2, 15, 44, 26, 343249)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 2, 15, 44, 26, 343219)),
        ),
    ]
