# Generated by Django 2.1.4 on 2019-01-05 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0005_auto_20190102_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('picture', models.ImageField(help_text='Insert the picture here', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('leave_type', models.IntegerField(choices=[(1, 'half day'), (2, 'full day')], default=1)),
                ('remark', models.CharField(help_text='Enter the reason of the leave', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(help_text='Price of the sold product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('product_total_price', models.IntegerField()),
                ('stock_update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('quantity', models.IntegerField(help_text='Enter the quantity of this product')),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='outlet',
            name='sec',
            field=models.OneToOneField(default=1, help_text='Enter the SEC of this outlet', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visit',
            name='foe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.Outlet'),
        ),
        migrations.AddField(
            model_name='target',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.Outlet'),
        ),
        migrations.AddField(
            model_name='target',
            name='productVariation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.ProductVariation'),
        ),
        migrations.AddField(
            model_name='stock',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.Outlet'),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(help_text='Enter the customer name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sales',
            name='outlet',
            field=models.ForeignKey(help_text='Enter the outlet name', on_delete=django.db.models.deletion.CASCADE, to='sales_management.Outlet'),
        ),
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(help_text='Enter the product name', on_delete=django.db.models.deletion.CASCADE, to='sales_management.ProductVariation'),
        ),
        migrations.AddField(
            model_name='leave',
            name='authorized_by',
            field=models.ForeignKey(help_text='Enter who authorized this leave', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leave',
            name='outlet',
            field=models.ForeignKey(help_text='Enter the outlet name', on_delete=django.db.models.deletion.CASCADE, to='sales_management.Outlet'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='outlet',
            field=models.ForeignKey(help_text='Enter the outlet', on_delete=django.db.models.deletion.CASCADE, to='sales_management.Outlet'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sec',
            field=models.ForeignKey(default=1, help_text='Enter the sec', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
