# Generated by Django 2.1.4 on 2019-01-05 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0006_auto_20190105_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sec',
            field=models.ForeignKey(help_text='Enter the sec', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
